### ISSUE TITLE
removeDefaultBookmarks seems not to work anymore on FF57

### ISSUE THREAD

**Issue by llelectronics** [mkaply/cck2wizard#69]
It seems like removeDefaultBookmarks is not working for FF57 anymore. 
It leaves "Getting Started" in the bookmarks toolbar.
Same cck2.cfg worked fine in FF56 and before.

**Comment by mkaply** [comment]
Have you updated to the latest CCK2?

**Comment by mkaply** [comment]
I've checked on this and it's working for me. Might be a timing issue.

I'l continue to investigate.

**Comment by shadeslayer** [comment]
I investigated this and turns out the userAgentLocale is undefined in our deployment of firefox 58
This line here https://github.com/mkaply/cck2wizard/blob/master/cck2/modules/CCK2.jsm#L663 seems to be the culprit.

However, general.useragent.locale is defined as en-us in about:config, so perhaps it's only undefined on the first run?

**Comment by shadeslayer** [comment]
So I've worked around it as such https://github.com/netrunner-common/netrunner-settings-firefox/commit/20e08bf8937155c7690b7437fc11beadbac44260

**Comment by mkaply** [comment]
FYI, I went a different route. This should be good in Firefox 60 with latest CCK2.
